export const REGIONAL_PARTNERS = [
    { name: "Puma", file: "puma.avif" },
    { name: "TATA", file: "tata.avif" },
    { name: "Aggreko", file: "aggreko.avif" },
    { name: "McDonald's", file: "mcdonalds.avif" },
    { name: "T-Mobile", file: "t-mobile.avif" },
    { name: "Fanatec", file: "fanatec.avif" },
];
export const GLOBAL_PARTNERS = [
    { name: "LVMH", file: "LVMH.avif" },
    { name: "Pirelli", file: "Pirelli.avif" },
    { name: "Aramco", file: "aramco.avif" },
    { name: "AWS", file: "aws-black.avif" },
    { name: "Lenovo", file: "Lenovo.avif" },
    { name: "DHL", file: "DHL.avif" },
    { name: "Qatar Airways", file: "qatar-airways.avif" },
    { name: "MSC", file: "MSC.avif" },
    { name: "Salesforce", file: "salesforce.avif" },
    { name: "Heineken", file: "Heineken.avif" },
]

export const OFFICIAL_PARTNERS = [
    { name: "Louis Vuitton", file: "louis-vuitton.avif" },
    { name: "TAG Heuer", file: "tag.avif" },
    { name: "American Express", file: "american-express.avif" },
    { name: "PepsiCo", file: "pepsico.avif" },
    { name: "Crypto.com", file: "crypto.avif" },
    { name: "Standard Chartered", file: "standard-chartered.avif" },
    { name: "Santander", file: "santander.avif" },
    { name: "Globant", file: "globant.avif" },
    { name: "Allwyn", file: "allwyn.avif" },
    { name: "PwC", file: "pwc.avif" },
    { name: "Nestlé", file: "nestle.avif" },
    { name: "Barilla", file: "barilla.avif" },
    { name: "Las Vegas", file: "las-vegas.avif" },
    { name: "Liqui Moly", file: "liqui-moly.avif" },
    { name: "Paramount+", file: "paramount.avif" },
    { name: "Moët", file: "moet.avif" },
]

export const TEAM_SHORT: Record<string, string> = {
    mclaren: "MCL", mercedes: "MER", red_bull: "RBR", ferrari: "FER",
    williams: "WIL", rb: "RB", aston_martin: "AM", haas: "HAA",
    kick_sauber: "SAU", alpine: "ALP",
}


export const DRIVER_IMAGES: Record<string, string> = {
    albon: "/F1/drivers/alexander-albon.avif",
    lindblad: "/F1/drivers/arvid-lindblad.avif",
    sainz: "/F1/drivers/carlos-sainz.avif",
    leclerc: "/F1/drivers/charles-leclerc.avif",
    ocon: "/F1/drivers/esteban-ocon.avif",
    alonso: "/F1/drivers/fernando-alonso.avif",
    colapinto: "/F1/drivers/franco-colapinto.avif",
    bortoleto: "/F1/drivers/gabriel-bortoleto.avif",
    russell: "/F1/drivers/george-russell.avif",
    hadjar: "/F1/drivers/isack-hadjar.avif",
    antonelli: "/F1/drivers/kimi-antonelli.avif",
    stroll: "/F1/drivers/lance-stroll.avif",
    norris: "/F1/drivers/lando-norris.avif",
    hamilton: "/F1/drivers/lewis-hamilton.avif",
    lawson: "/F1/drivers/liam-lawson.avif",
    max_verstappen: "/F1/drivers/max-verstappen.avif",
    hulkenberg: "/F1/drivers/nico-hulkenberg.avif",
    bearman: "/F1/drivers/oliver-bearman.avif",
    piastri: "/F1/drivers/oscar-piastri.avif",
    gasly: "/F1/drivers/pierre-gasly.avif",
    perez: "/F1/drivers/sergio-perez.avif",
    bottas: "/F1/drivers/valtteri-bottas.avif",
    doohan: "/F1/drivers/jack-doohan.avif",
    tsunoda: "/F1/drivers/yuki-tsunoda.avif",
    mick_schumacher: "/F1/drivers/MickSchumacher.avif",
    arvid_lindblad: "/F1/drivers/arvid-lindblad.avif",
    kevin_magnussen: "/F1/drivers/kevin-magnussen.png",
    ricciardo: "/F1/drivers/daniel-ricciardo.png",
    zhou: "/F1/drivers/guanyu-zhou.png",
    sargeant: "/F1/drivers/logan-sargeant.png",
    de_vries: "/F1/drivers/nyck-de-vries.png",
    vettel: "/F1/drivers/sebastian-vettel.png",
    sirotkin: "/F1/drivers/sergey-sirotkin.png",
    latifi: "/F1/drivers/nicholas-latifi.png",
    giovinazzi: "/F1/drivers/antonio-giovinazzi.png",
    kubica: "/F1/drivers/robert-kubica.png",
    mazepin: "/F1/drivers/nikita-mazepin.png",
    raikkonen: "/F1/drivers/kimi-räikkönen.png",
    grosjean: "/F1/drivers/romain-grosjean.png",
    ericsson: "/F1/drivers/marcus-ericsson.png",
    brendon_hartley: "/F1/drivers/brendon-hartley.png",
    vandoorne: "/F1/drivers/stoffel-vandoorne.png",
    kvyat: "/F1/drivers/daniil-kvyat.png",

};

export const TEAM_CARS: Record<string, string> = {
    mclaren: "/F1/team/2026mclarencarright.avif",
    mercedes: "/F1/team/2026mercedescarright.avif",
    red_bull: "/F1/team/2026redbullracingcarright.avif",
    ferrari: "/F1/team/2026ferraricarright.avif",
    williams: "/F1/team/2026williamscarright.avif",
    rb: "/F1/team/2026racingbullscarright.avif",
    aston_martin: "/F1/team/2026astonmartincarright.avif",
    haas: "/F1/team/2026haascarright.avif",
    kick_sauber: "/F1/team/2026audicarright.avif",
    alpine: "/F1/team/2026alpinecarright.avif",
    audi: "/F1/team/2026audicarright.avif",
    cadillac: "/F1/team/2026cadillaccarright.avif",
    alphatauri: "/F1/team/alphaTauri.png",
    renault: "/F1/team/renault.png",
    force_india: "/F1/team/force-india.png",
    sauber: "/F1/team/2025kicksaubercarright.avif",
    toro_rosso: "/F1/team/toro-rosso.png",
    racing_point: "/F1/team/racing-point.png",
    alfa: "/F1/team/alfa.png",
}

export const TEAM_LOGOS: Record<string, string> = {
    mclaren: "/F1/logos/mclarenlogowhite.webp",
    mercedes: "/F1/logos/mercedeslogowhite.webp",
    red_bull: "/F1/logos/redbullracinglogowhite.webp",
    ferrari: "/F1/logos/ferrarilogolight.webp",
    williams: "/F1/logos/williamslogowhite.webp",
    rb: "/F1/logos/racingbullslogowhite.webp",
    aston_martin: "/F1/logos/astonmartinlogowhite.webp",
    haas: "/F1/logos/haaslogowhite.webp",
    kick_sauber: "/F1/logos/audilogowhite.webp",
    alpine: "/F1/logos/alpinelogowhite.webp",
    audi: "/F1/logos/audilogowhite.webp",
    cadillac: "/F1/logos/cadillaclogowhite.webp",
}

export const FALLBACK_DRIVER = "/F1/drivers/driver-placeholder.png"
export const FALLBACK_CAR = "/F1/team/CAR.png"
export const FALLBACK_LOGO = "/F1/logos/formula-1-log.png"

export const PODIUM = {
    colors: ["#F5C842", "#C0C0C0", "#CD7F32"],
    labels: ["1ST", "2ND", "3RD"],
    heights: ["240px", "210px", "200px"],
}

export const CIRCUIT_COLORS: Record<string, string> = {
    bahrain: "#E10600",
    jeddah: "#00B4D8",
    albert_park: "#2ECC71",
    suzuka: "#FF6B00",
    shanghai: "#F5C842",
    miami: "#00A3E0",
    imola: "#E10600",
    monaco: "#F5C842",
    villeneuve: "#FF0000",
    catalunya: "#FFCC00",
    red_bull_ring: "#1E90FF",
    silverstone: "#CCCCCC",
    hungaroring: "#E10600",
    spa: "#00A651",
    zandvoort: "#FF6B00",
    monza: "#E10600",
    baku: "#00B4D8",
    marina_bay: "#F5C842",
    americas: "#FF6B00",
    rodriguez: "#2ECC71",
    interlagos: "#00A651",
    las_vegas: "#F5C842",
    losail: "#00B4D8",
    yas_marina: "#1E90FF",
    madrid: "#E10600",
}

export const CIRCUIT_IMAGES: Record<string, string> = {
    americas: "/F1/circuits/images/circuit-of-the-americas.avif",
    miami: "/F1/circuits/images/miami-international-autodrome.avif",
    albert_park: "/F1/circuits/images/albert-park-grand-prix-circuit.avif",
    bahrain: "/F1/circuits/images/bahrain-international-circuit.avif",
    interlagos: "/F1/circuits/images/autdromo-jos-carlos-pace.avif",
    baku: "/F1/circuits/images/baku-city-circuit.avif",
    vegas: "/F1/circuits/images/las-vegas-strip-street-circuit.avif",
    spa: "/F1/circuits/images/circuit-de-spa-francorchamps.avif",
    red_bull_ring: "/F1/circuits/images/red-bull-ring.avif",
    silverstone: "/F1/circuits/images/silverstone-circuit.avif",
    yas_marina: "/F1/circuits/images/yas-marina-circuit.avif",
    istanbul: "/F1/circuits/images/istanbul-park.avif",
    madring: "/F1/circuits/images/madring.avif",
    catalunya: "/F1/circuits/images/circuit-de-barcelona-catalunya.avif",
    villeneuve: "/F1/circuits/images/circuit-gilles-villeneuve.avif",
    shanghai: "/F1/circuits/images/shanghai-international-circuit.avif",
    ricard: "/F1/circuits/images/circuit-paul-ricard.avif",
    nurburgring: "/F1/circuits/images/nrburgring.avif",
    hockenheimring: "/F1/circuits/images/hockenheim.avif",
    hungaroring: "/F1/circuits/images/hungaroring.avif",
    mugello: "/F1/circuits/images/autodromo-internazionale-del-mugello.avif",
    monza: "/F1/circuits/images/autodromo-nazionale-di-monza.avif",
    imola: "/F1/circuits/images/autodromo-enzo-e-dino-ferrari.avif",
    suzuka: "/F1/circuits/images/suzuka-circuit.avif",
    rodriguez: "/F1/circuits/images/autdromo-hermanos-rodrguez.avif",
    monaco: "/F1/circuits/images/circuit-de-monaco.avif",
    zandvoort: "/F1/circuits/images/circuit-park-zandvoort.avif",
    portimao: "/F1/circuits/images/autódromo-internacional-do-algarve.avif",
    losail: "/F1/circuits/images/losail-international-circuit.avif",
    sochi: "/F1/circuits/images/sochi-autodrom.avif",
    jeddah: "/F1/circuits/images/jeddah-corniche-circuit.avif",
    marina_bay: "/F1/circuits/images/marina-bay-street-circuit.avif",


}

export const CURRENT_SEASON = new Date().getFullYear().toString()
export const AVAILABLE_SEASONS = Array.from(
    { length: new Date().getFullYear() - 2018 + 1 },
    (_, i) => String(new Date().getFullYear() - i)
)